# frozen_string_literal: true

module TurnKit
  # Persists TurnKit records through ActiveRecord model classes generated by
  # `rails g turnkit:install`.
  #
  # Note the namespaces: TurnKit:: is this gem's domain layer; the generated
  # Rails models live under Turnkit:: (Rails-inflection friendly) and are pure
  # persistence records. Turnkit::Conversation (a database row) is not
  # TurnKit::Conversation (the domain object).
  class ActiveRecordStore < Store
    def initialize(conversation_class: "Turnkit::Conversation", turn_class: "Turnkit::Turn", message_class: "Turnkit::Message", tool_execution_class: "Turnkit::ToolExecution", delivery_class: "Turnkit::Delivery", wait_class: "Turnkit::Wait")
      @conversation_class_name = conversation_class
      @turn_class_name = turn_class
      @message_class_name = message_class
      @tool_execution_class_name = tool_execution_class
      @delivery_class_name = delivery_class
      @wait_class_name = wait_class
    end

    def atomic(conversation_id)
      conversation_class.connection_pool.with_connection do
        conversation_class.transaction do
          conversation_class.lock.find_by!(uid: conversation_id)
          yield
        end
      end
    end

    # Wait-graph mutations use one database-wide transaction lock. PostgreSQL
    # advisory xact locks serialize opposite edges even when roots differ.
    def atomic_graph
      conversation_class.connection_pool.with_connection do |connection|
        conversation_class.transaction do
          raise ConfigError, "atomic wait graphs require PostgreSQL" unless connection.adapter_name.match?(/postg/i)
          connection.execute("SELECT pg_advisory_xact_lock(1414876747)")
          yield
        end
      end
    end

    def create_conversation(attributes)
      record = conversation_class.create!(record_attributes(attributes, id_key: "uid"))
      conversation_hash(record)
    end

    def load_conversation(id)
      conversation_hash(conversation_class.find_by!(uid: id))
    end

    def next_message_sequence(conversation_id)
      conversation_class.transaction do
        conversation = conversation_class.lock.find_by!(uid: conversation_id)
        message_class.where(conversation_uid: conversation.uid).maximum(:sequence).to_i + 1
      end
    end

    def latest_message_sequence(conversation_id)
      message_class.where(conversation_uid: conversation_id).maximum(:sequence).to_i
    end

    def append_message(attributes)
      attrs = attributes.transform_keys(&:to_s)
      sequence = nil
      message = nil
      record = conversation_class.transaction do
        conversation_class.lock.find_by!(uid: attrs.fetch("conversation_id"))
        sequence = message_class.where(conversation_uid: attrs.fetch("conversation_id")).maximum(:sequence).to_i + 1
        message = Record.message(attrs.merge("sequence" => sequence))
        message_class.create!(
          uid: message.fetch("id"),
          conversation_uid: message.fetch("conversation_id"),
          turn_uid: message["turn_id"],
          role: message.fetch("role"),
          kind: message.fetch("kind"),
          sequence: message.fetch("sequence"),
          content: message.fetch("content"),
          tool_execution_uid: message["tool_execution_id"],
          provider_message_id: message["provider_message_id"],
          metadata: message.fetch("metadata")
        )
      end
      message_hash(record)
    end

    def list_messages(conversation_id, through_sequence: nil, turn_id: nil)
      scope = message_class.where(conversation_uid: conversation_id)
      if through_sequence
        scope = scope.where("sequence <= ? OR turn_uid = ?", through_sequence, turn_id)
      end
      scope.order(:sequence, :created_at, :uid).map { |record| message_hash(record) }
    end

    def create_turn(attributes)
      attrs = Record.turn(attributes)
      record_attrs = {
        uid: attrs.fetch("id"),
        conversation_uid: attrs.fetch("conversation_id"),
        agent_name: attrs["agent_name"],
        parent_turn_uid: attrs["parent_turn_id"],
        parent_tool_execution_uid: attrs["parent_tool_execution_id"],
        root_turn_uid: attrs.fetch("root_turn_id"),
        context_message_sequence: attrs["context_message_sequence"].to_i,
        status: attrs.fetch("status"),
        model: attrs["model"],
        options: attrs["options"] || {},
        usage: attrs["usage"] || {},
        cost: attrs["cost"],
        error: attrs["error"],
        output_text: attrs["output_text"],
        submitted_at: attrs["submitted_at"],
        claim_token: attrs["claim_token"],
        started_at: attrs["started_at"],
        heartbeat_at: attrs["heartbeat_at"],
        completed_at: attrs["completed_at"]
      }
      record_attrs[:output_data] = attrs["output_data"] if turn_has_attribute?("output_data")
      record = turn_class.create!(record_attrs)
      turn_hash(record)
    end

    def load_turn(id)
      turn_hash(turn_class.find_by!(uid: id))
    end

    def update_turn(id, attributes)
      record = turn_class.find_by!(uid: id)
      attrs = Record.turn_update(attributes)
      attrs.delete("output_data") unless turn_has_attribute?("output_data")
      record.update!(attrs)
      turn_hash(record)
    end

    def claim_turn(id, from: "pending", to: "running", **attributes)
      attrs = Record.turn_update(attributes.merge(status: to))
      attrs.delete("output_data") unless turn_has_attribute?("output_data")
      affected = turn_class.where(uid: id, status: from).update_all(attrs.merge(updated_at: Clock.now))
      return nil if affected.zero?

      load_turn(id)
    end

    def list_turns(root_turn_id: nil, conversation_id: nil, agent_name: nil)
      scope = turn_class.all
      scope = scope.where(root_turn_uid: root_turn_id) if root_turn_id
      scope = scope.where(conversation_uid: conversation_id) if conversation_id
      scope = scope.where(agent_name: agent_name) if agent_name
      scope.order(:created_at, :uid).map { |record| turn_hash(record) }
    end

    def list_submitted_turns(limit: nil)
      scope = turn_class.where.not(submitted_at: nil).order(:created_at, :uid)
      scope = scope.limit(limit) if limit
      scope.map { |record| turn_hash(record) }
    end

    def list_actionable_turns(limit:)
      turn_class.where.not(submitted_at: nil).where(status: %w[pending waiting running]).order(:updated_at, :uid).limit(limit).map { |record| turn_hash(record) }
    end

    def list_stale_inline_turns(before:, limit:)
      turn_class.where(submitted_at: nil, status: %w[pending running])
        .where("COALESCE(heartbeat_at, started_at, created_at) < ?", before)
        .order(:updated_at, :uid).limit(limit).map { |record| turn_hash(record) }
    end

    def busy_conversation?(id, include_pending: true)
      turns = turn_class.where(conversation_uid: id)
      active = turns.where(status: %w[running waiting])
      active = active.or(turns.where(status: "pending").where.not(submitted_at: nil)) if include_pending
      active.exists?
    end

    def next_delivery_trigger(id)
      consumed = turn_class.where(conversation_uid: id).where.not(status: "pending", submitted_at: nil).maximum(:context_message_sequence).to_i
      delivered_ids = delivery_class.where(destination_conversation_uid: id).where.not(message_uid: nil).select(:message_uid)
      message = message_class.where(conversation_uid: id, uid: delivered_ids).where("sequence > ?", consumed).order(sequence: :desc).first
      message_hash(message) if message
    end

    def create_delivery(attributes)
      attrs = Record.delivery(attributes)
      record = delivery_class.create_or_find_by!(key: attrs.fetch("key")) do |delivery|
        delivery.uid = attrs.fetch("id")
        delivery.source_conversation_uid = attrs.fetch("source_conversation_id")
        delivery.destination_conversation_uid = attrs.fetch("destination_conversation_id")
        delivery.source_turn_uid = attrs["source_turn_id"]
        delivery.payload = attrs.fetch("payload")
        delivery.message_uid = attrs["message_id"]
        delivery.delivered_at = attrs["delivered_at"]
        delivery.created_at = attrs.fetch("created_at")
      end
      existing = delivery_hash(record)
      Record.assert_delivery_retry!(existing, attrs)
      existing
    end

    def load_delivery(id)
      delivery_hash(delivery_class.find_by!(uid: id))
    end

    def update_delivery(id, attributes)
      record = delivery_class.find_by!(uid: id)
      record.update!(Record.delivery_update(attributes).transform_keys { |key| key == "message_id" ? "message_uid" : key })
      delivery_hash(record)
    end

    def list_deliveries(source_conversation_id: nil, destination_conversation_id: nil, pending: false, limit: nil)
      scope = delivery_class.all
      scope = scope.where(source_conversation_uid: source_conversation_id) if source_conversation_id
      scope = scope.where(destination_conversation_uid: destination_conversation_id) if destination_conversation_id
      scope = scope.where(delivered_at: nil) if pending
      scope = scope.order(:created_at, :uid)
      scope = scope.limit(limit) if limit
      scope.map { |record| delivery_hash(record) }
    end

    def create_wait(turn_id:, target_turn_id:)
      record = wait_class.create_or_find_by!(turn_uid: turn_id, target_turn_uid: target_turn_id)
      wait_hash(record)
    end

    def list_waits(turn_id: nil, target_turn_id: nil)
      scope = wait_class.all
      scope = scope.where(turn_uid: turn_id) if turn_id
      scope = scope.where(target_turn_uid: target_turn_id) if target_turn_id
      scope.order(:id).map { |record| wait_hash(record) }
    end

    def create_tool_execution(attributes)
      attrs = Record.tool_execution(attributes)
      record = tool_execution_class.create!(
        uid: attrs.fetch("id"),
        turn_uid: attrs.fetch("turn_id"),
        tool_call_id: attrs.fetch("tool_call_id"),
        tool_name: attrs.fetch("tool_name"),
        status: attrs.fetch("status"),
        arguments: attrs["arguments"] || {},
        result: attrs["result"],
        error: attrs["error"],
        started_at: attrs["started_at"],
        completed_at: attrs["completed_at"]
      )
      tool_execution_hash(record)
    end

    def load_tool_execution(id)
      tool_execution_hash(tool_execution_class.find_by!(uid: id))
    end

    def claim_tool_execution(id, from: "running", to: "completed", **attributes)
      attrs = Record.tool_execution_update(attributes.merge(status: to))
      affected = tool_execution_class.where(uid: id, status: from).update_all(attrs.merge(updated_at: Clock.now))
      return nil if affected.zero?

      load_tool_execution(id)
    end

    def list_tool_executions(turn_id:)
      tool_execution_class.where(turn_uid: turn_id).order(:created_at, :uid).map { |record| tool_execution_hash(record) }
    end

    private
      def conversation_class = constantize(@conversation_class_name)
      def turn_class = constantize(@turn_class_name)
      def message_class = constantize(@message_class_name)
      def tool_execution_class = constantize(@tool_execution_class_name)
      def delivery_class = constantize(@delivery_class_name)
      def wait_class = constantize(@wait_class_name)

      def constantize(name)
        name.to_s.split("::").inject(Object) { |mod, part| mod.const_get(part) }
      end

      def record_attributes(attributes, id_key:)
        attrs = Record.conversation(attributes)
        subject_type, subject_id = Record.subject_pair(attrs["subject"])
        {
          id_key => attrs.fetch("id"),
          agent_name: attrs["agent_name"],
          model: attrs["model"],
          subject_type: subject_type,
          subject_id: subject_id,
          metadata: attrs["metadata"] || {}
        }
      end

      def conversation_hash(record)
        { "id" => record.uid, "agent_name" => record.agent_name, "model" => record.model,
          "subject" => record.subject_type && { "type" => record.subject_type, "id" => record.subject_id },
          "metadata" => record.metadata || {}, "created_at" => record.created_at, "updated_at" => record.updated_at }
      end

      def turn_hash(record)
        attrs = {
          "id" => record.uid, "conversation_id" => record.conversation_uid, "agent_name" => record.agent_name,
          "parent_turn_id" => record.parent_turn_uid, "parent_tool_execution_id" => record.parent_tool_execution_uid,
          "root_turn_id" => record.root_turn_uid, "context_message_sequence" => record.context_message_sequence,
          "status" => record.status, "model" => record.model, "options" => record.options || {}, "usage" => record.usage || {},
          "cost" => record.cost, "error" => record.error, "output_text" => record.output_text,
          "submitted_at" => record.submitted_at, "claim_token" => record.claim_token,
          "started_at" => record.started_at, "heartbeat_at" => record.heartbeat_at, "completed_at" => record.completed_at,
          "created_at" => record.created_at, "updated_at" => record.updated_at
        }
        attrs["output_data"] = record.output_data if record.respond_to?(:output_data)
        attrs
      end

      def delivery_hash(record)
        {
          "id" => record.uid, "source_conversation_id" => record.source_conversation_uid,
          "destination_conversation_id" => record.destination_conversation_uid, "source_turn_id" => record.source_turn_uid,
          "key" => record.key, "payload" => record.payload || {}, "message_id" => record.message_uid,
          "delivered_at" => record.delivered_at, "created_at" => record.created_at
        }
      end

      def wait_hash(record)
        { "turn_id" => record.turn_uid, "target_turn_id" => record.target_turn_uid }
      end

      def turn_has_attribute?(name)
        turn_class.respond_to?(:attribute_names) && turn_class.attribute_names.include?(name)
      end

      def message_hash(record)
        {
          "id" => record.uid, "conversation_id" => record.conversation_uid, "turn_id" => record.turn_uid,
          "role" => record.role, "kind" => record.kind, "sequence" => record.sequence, "content" => record.content,
          "tool_execution_id" => record.tool_execution_uid,
          "provider_message_id" => record.provider_message_id, "metadata" => record.metadata || {}, "created_at" => record.created_at
        }
      end

      def tool_execution_hash(record)
        {
          "id" => record.uid, "turn_id" => record.turn_uid, "tool_call_id" => record.tool_call_id,
          "tool_name" => record.tool_name, "status" => record.status, "arguments" => record.arguments || {},
          "result" => record.result, "error" => record.error, "started_at" => record.started_at, "completed_at" => record.completed_at
        }
      end
  end
end
