# frozen_string_literal: true

$LOAD_PATH.unshift(File.expand_path("../lib", __dir__))

require "turnkit"

class ManualCompactionClient < TurnKit::Client
  attr_reader :calls

  def initialize
    @calls = []
  end

  def chat(model:, messages:, tools:, instructions:, temperature: nil, thinking: nil, metadata: nil)
    @calls << { model: model, messages: messages, tools: tools, instructions: instructions, metadata: metadata }

    if metadata&.fetch(:compaction, false)
      TurnKit::Result.new(text: <<~SUMMARY, model: model)
        ## Active Task
        - Continue answering the latest user request.

        ## Goal
        - Demonstrate TurnKit context compaction.

        ## Constraints & Preferences
        - Keep original messages durable.

        ## Completed Actions
        - Added several long user messages to the conversation.

        ## Active State
        - A compaction summary is being generated by the manual test client.

        ## In Progress
        - (none)

        ## Blocked
        - (none)

        ## Key Decisions
        - Store summaries as context_summary messages instead of deleting old messages.

        ## Resolved Questions
        - (none)

        ## Pending User Asks
        - Continue after compaction.

        ## Relevant Files
        - script/manual_compaction.rb: one-off manual compaction smoke test.

        ## Tool Results To Remember
        - (none)

        ## Remaining Work
        - Inspect printed durable and projected message counts.

        ## Critical Context
        - This summary was generated locally without calling a real model.
      SUMMARY
    else
      roles = messages.map { |message| message.fetch(:role) }.join(" -> ")
      TurnKit::Result.new(text: "Main model saw #{messages.length} projected messages: #{roles}", model: model)
    end
  end
end

TurnKit.store = TurnKit::MemoryStore.new
TurnKit.default_model = "main-model"
TurnKit.compaction = {
  model: "summary-model",
  context_limit: 160,
  reserved_tokens: 0,
  threshold: 0.2,
  head_messages: 0,
  tail_messages: 1,
  tail_tokens: 10_000
}

client = ManualCompactionClient.new
agent = TurnKit::Agent.new(name: "manual", client: client)
conversation = agent.conversation

6.times do |i|
  conversation.say("Long durable message #{i}: #{"x" * 80}")
end

turn = conversation.ask("Continue after compaction")
projected = TurnKit::Compaction.project(conversation.messages)

puts "Turn status: #{turn.status}"
puts "Turn output: #{turn.output_text}"
puts "Client calls: #{client.calls.length}"
puts "Durable messages: #{conversation.messages.length}"
puts "Projected messages: #{projected.length}"
puts "Summary messages: #{conversation.messages.count(&:context_summary?)}"
puts "Projected kinds: #{projected.map(&:kind).join(" -> ")}"
