# frozen_string_literal: true

source "https://rubygems.org"

gemspec path: "../.."
gem "minitest"
gem "rake"
gem "ruby_llm", "~> 1.16"
gem "activerecord", "~> 8.1.0"
gem "activejob", "~> 8.1.0"
gem "railties", "~> 8.1.0"
gem "pg"
gem "solid_queue", "~> 1.3"
gem "sidekiq", "~> 8.1"
